GET http://localhost:3001/api/people

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/people/683f326d8073630af898ac6a

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/people/684b49ca8c1af3dbb2db7def

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Guillermo 2",
    "phone": "91-642940"
}

###
PUT http://localhost:3001/api/people/683f326d8073630af898ac6a
Content-Type: application/json

{
    "name": "Guillermo 2",
    "phone": "951-6402964"
}